# 本番環境設定
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: true