# 本番環境設定
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:public}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # 認可サーバーのエンドポイントを設定
          issuer-uri: http://keycloak:8080/realms/myrealm
